# SPDX-License-Identifier: MIT
# Spear · KILROY product boot — no casper
# Every cmdline token: speed + harden. Debug entry is the only verbose path.
timeout: 0
quiet: yes
verbose: no
default_entry: 2
# entry 2 = Field (after Debug at 1)
serial: yes
serial_baudrate: 115200
editor_enabled: no
hash_mismatch_panic: no
interface_branding: SPEAR · KILROY
interface_branding_colour: 2
interface_resolution: 1920x1080
term_background: ff0a1020
term_foreground: ffffff
term_foreground_bright: 00e6ff
term_margin: 40
term_font_scale: 2x2
wallpaper: boot():/boot/face/themes/field/wallpaper.bmp
wallpaper_style: centered
backdrop: 000000

# Shared harden flags (KILROY path)
# spear_harden=1 · quiet · serial · apparmor-like userspace expects field=1

/Debug
comment: verbose serial · field diagnostics · ash
protocol: linux
path: boot():/boot/kilroy/vmlinuz-lab
module_path: boot():/boot/kilroy/initramfs.cpio.gz
cmdline: field=1 spear_mode=debug spear_debug=1 spear_harden=1 root=/dev/ram0 rw init=/init console=tty0 console=ttyS0,115200n8 earlyprintk=serial,ttyS0,115200 loglevel=8 debug ignore_loglevel page_alloc.shuffle=1 randomize_kstack_offset=on slab_nomerge pti=on

/Field
comment: FAST path · field-native · no desktop · default
protocol: linux
path: boot():/boot/kilroy/vmlinuz-lab
module_path: boot():/boot/kilroy/initramfs.cpio.gz
cmdline: field=1 spear_mode=field spear_harden=1 spear_fast=1 root=/dev/ram0 rw init=/init console=tty0 console=ttyS0,115200n8 quiet loglevel=3 tsc=reliable pti=on

/Normal
comment: full path · heavier than Field
protocol: linux
path: boot():/boot/kilroy/vmlinuz-lab
module_path: boot():/boot/kilroy/initramfs.cpio.gz
cmdline: field=1 spear_mode=normal spear_harden=1 root=/dev/ram0 rw init=/init console=tty0 console=ttyS0,115200n8 quiet loglevel=3 page_alloc.shuffle=1 randomize_kstack_offset=on slab_nomerge pti=on

/Create Field Drive
comment: wipe/create Field1 · secure MBR + FFAT
protocol: linux
path: boot():/boot/kilroy/vmlinuz-lab
module_path: boot():/boot/kilroy/initramfs.cpio.gz
cmdline: field=1 spear_mode=fielddrive spear_harden=1 spear_fast=1 root=/dev/ram0 rw init=/init console=tty0 console=ttyS0,115200n8 quiet loglevel=3 tsc=reliable pti=on

/Compat
comment: Field RAM always · Field Drive optional
protocol: linux
path: boot():/boot/kilroy/vmlinuz-lab
module_path: boot():/boot/kilroy/initramfs.cpio.gz
cmdline: field=1 spear_mode=compat spear_harden=1 root=/dev/ram0 rw init=/init console=tty0 console=ttyS0,115200n8 quiet loglevel=3 tsc=reliable pti=on

/War
comment: max CPU mitigations (slower)
protocol: linux
path: boot():/boot/kilroy/vmlinuz-lab
module_path: boot():/boot/kilroy/initramfs.cpio.gz
cmdline: field=1 spear_mode=normal spear_harden=1 spear_war=1 root=/dev/ram0 rw init=/init console=tty0 console=ttyS0,115200n8 quiet loglevel=3 page_alloc.shuffle=1 randomize_kstack_offset=on slab_nomerge pti=on spectre_v2=on spec_store_bypass_disable=prctl l1tf=flush mds=full tsx=off
